name:Nickki

on: [push]

jobs:ช่วยเหลือสังคม เป็นจิตอาสา
  build:คุณค่าให้ตัวเราเอง

    runs-on:ล่าสุด

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
